// Renders the "Casey Rules" tab — a static reference summary of Dr. Casey
// Means' 5 IN / 3 OUT framework, shopping rules, and the items the user
// chose to keep ("✎ Manual") despite not being on Casey's official list.
//
// This content mirrors docs/PROFILE.md and Meal_Plan_English.md / Plan_
// Alimentacion_Espanol.md. If you change the rules here, update those too
// (or better: extract to data and render from a single source — see TODO.md).

import { el } from '../dom.js';

export function renderRules() {
  return el('div', { class: 'rules-page' },
    el('div', { class: 'rule-block' },
      el('h2', {}, 'Dr. Casey\'s 5 In · 3 Out Framework'),
      el('div', { class: 'in-out-grid' },
        el('div', { class: 'in-out-card in-card' },
          el('h3', {}, '5 IN — eat daily'),
          el('ul', {},
            el('li', {}, el('strong', {}, 'Omega-3 fats: '), '≥ 2 g/day'),
            el('li', {}, el('strong', {}, 'Probiotics: '), '≥ 3 servings/day'),
            el('li', {}, el('strong', {}, 'Micronutrients/Antioxidants: '), 'Colorful plant diversity + spices'),
            el('li', {}, el('strong', {}, 'Fiber: '), '> 50 g/day'),
            el('li', {}, el('strong', {}, 'Protein: '), '≥ 30 g per meal'),
          ),
        ),
        el('div', { class: 'in-out-card out-card' },
          el('h3', {}, '3 OUT — avoid'),
          el('ul', {},
            el('li', {}, el('strong', {}, 'Refined/added sugars '), 'of any kind'),
            el('li', {}, el('strong', {}, 'Refined grains '), 'of any kind'),
            el('li', {}, el('strong', {}, 'Industrial seed oils: '), 'canola, soybean, corn, sunflower, safflower, cottonseed, palm, rapeseed'),
          ),
        ),
      ),
    ),
    el('div', { class: 'rule-block' },
      el('h2', {}, 'Shopping rules'),
      el('ul', {},
        el('li', {}, 'Buy almost exclusively whole, real, minimally processed foods.'),
        el('li', {}, 'Aim for organic always (or regeneratively grown).'),
        el('li', {}, 'No refined sugars and no "Added sugar" on the label.'),
        el('li', {}, 'ZERO refined industrial seed oils in the ingredient list.'),
        el('li', {}, 'No refined grains: avoid "wheat flour," "oat flour," "white flour."'),
        el('li', {}, 'No artificial colorings.'),
        el('li', {}, 'No "natural flavors" unless the brand specifies the source.'),
        el('li', {}, 'Frozen is OK as long as it adheres to these rules.'),
      ),
    ),
    el('div', { class: 'rule-block' },
      el('h2', {}, 'Animal product rules'),
      el('ul', {},
        el('li', {}, el('strong', {}, 'Meat & poultry: '), 'organic + grass-fed/pasture-raised/regenerative.'),
        el('li', {}, el('strong', {}, 'Fish: '), 'sustainably wild-caught; canned in olive oil or water only.'),
        el('li', {}, el('strong', {}, 'Dairy: '), 'organic + grass-fed/pasture-raised.'),
        el('li', {}, el('strong', {}, 'Eggs: '), 'organic + pasture-raised (cage-free does NOT count).'),
      ),
    ),
    el('div', { class: 'rule-block' },
      el('h2', {}, 'Allowed cooking fats'),
      el('p', {}, 'Extra virgin olive oil · Avocado oil · Coconut oil · Ghee · Grass-fed beef tallow · Pasture-raised lard'),
    ),
    el('div', { class: 'rule-block' },
      el('h2', {}, 'Manually added items'),
      el('p', {}, 'Items marked ✎ Manual are not on Dr. Casey\'s list but were kept based on your decisions:'),
      el('ul', {},
        el('li', {}, 'Ezekiel sprouted bread'),
        el('li', {}, 'Rolled / steel-cut oats (organic, no instant)'),
        el('li', {}, '1% milk'),
        el('li', {}, 'Quinoa (pseudograin)'),
        el('li', {}, 'Sweet potato (batata), malanga, yautía'),
        el('li', {}, 'Tostón / plantain (air-fried or fried in approved oils only)'),
        el('li', {}, 'Mushrooms (organic only)'),
        el('li', {}, 'Chayote (organic only)'),
      ),
    ),
  );
}
